### PR TITLE
Python 3.12

### PR DESCRIPTION
**Pull request by augustopher**
Upgrades the conda environment to Python 3.12, with small tweaks to the other packages to match.

### CODE REVIEW

**Comment by augustopher** [comment]
Looks like there's an old dependency in papermill's install that is restricted to 3.11? I can't install papermill locally (for other dumb dependency reasons).

Might have to hold off on this for the March class, and do it for the next round.

**Comment by augustopher** [comment]
The environment builds just fine (both locally and in GHA), it's just the papermill addition for the CI that's causing an issue.

**Review by jaycunningham-8451 — APPROVED** [review]
This looks fine to me!

**Comment by augustopher** [comment]
Well, just waiting a month seems to have resolved the dependency issue somewhere.

**Pull request merged**
